[program:]
process_name=%(program_name)s_%(process_num)02d
command=
autostart=true
autorestart=true
user=
numprocs=1
startsecs=1
redirect_stderr=true
stdout_logfile=
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stopwaitsecs=5
stopsignal=SIGTERM
stopasgroup=true
killasgroup=true
